### ISSUE TITLE
Rails 5.1 w/o jbuilder: undefined method `helper' for ActionController::API:Class

### ISSUE THREAD

**Issue by robcole** [devnacho/mountain_view#52]
Our tests began failing in a Rails 5.1.1 app when jbuilder was removed.

App: Rails 5.1.1, without jbuilder, triggers this when running `rspec spec`. With `jbuilder` installed, tests pass. I'm a bit confused about why this would be from reading through jbuilder's code, but calling the helper method explicitly seems to fix it. I can try to reproduce this error in a clean app for you if you needed it, but #53 fixes this in my setup.

Let me know if you have more questions! Here's the error log:

```
NoMethodError:
  undefined method `helper' for ActionController::API:Class
# ./vendor/gems/mountain_view/lib/mountain_view/engine.rb:34:in `block (2 levels) in <class:Engine>'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /bundle/gems/actionpack-5.1.1/lib/action_controller/api.rb:145:in `<class:API>'
# /bundle/gems/actionpack-5.1.1/lib/action_controller/api.rb:87:in `<module:ActionController>'
# /bundle/gems/actionpack-5.1.1/lib/action_controller/api.rb:5:in `<top (required)>'
# /bundle/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
# /bundle/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
# /bundle/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
# /bundle/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
# /bundle/gems/fastly-rails-0.8.0/lib/fastly-rails/engine.rb:16:in `block in <class:Engine>'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /bundle/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
```

**Comment by robcole** [comment]
Hey guys, I have a fix for this coming in a PR - just making sure all tests pass currently before I push a PR to my forked branch, and then to here.

**Comment by kitop** [comment]
Hi @robcole thanks for this!
Seems to be related to #51, right?

**Comment by snuggs** [comment]
Yup @kitop! Interesting Github didn't "Auto close" the project. Must be from maintainers only. /cc @robcole

**Comment by snuggs** [comment]
@kitop 🙏
