### ISSUE TITLE
undefined method `render_component' 

### ISSUE THREAD

**Issue by kimadactyl** [devnacho/mountain_view#57]
Heya, not sure if linked to #56 or not but after the update I'm getting this. Header is a basic component with nothing fancy going on. 

```
kim@haraway:~/git/taichi/taichi.school$ be rails s webrick
=> Booting WEBrick
=> Rails 4.2.9 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/kim/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
[2017-08-08 12:07:23] INFO  WEBrick 1.3.1
[2017-08-08 12:07:23] INFO  ruby 2.4.1 (2017-03-22) [x86_64-linux]
[2017-08-08 12:07:23] INFO  WEBrick::HTTPServer#start: pid=8040 port=3000


Started GET "/" for 127.0.0.1 at 2017-08-08 12:07:26 +0100
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by StaticPagesController#home as HTML
/home/kim/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/versioncake-2.3.1/lib/versioncake/strategies/extraction_strategy.rb:8: warning: constant ::Fixnum is deprecated
  Notification Load (0.4ms)  SELECT  "notifications".* FROM "notifications" WHERE "notifications"."is_active" = $1  ORDER BY "notifications"."id" DESC LIMIT 1  [["is_active", "t"]]
  Rendered layouts/_mailinglist.erb (0.3ms)
  Rendered static_pages/home.html.erb within layouts/application (1320.7ms)
  Rendered layouts/_facebook.html.erb (0.3ms)
  Rendered layouts/_alerts.html.erb (0.4ms)
Completed 500 Internal Server Error in 1505ms (ActiveRecord: 4.4ms)

NoMethodError - undefined method `render_component' for #<#<Class:0x0056547eb10188>:0x0056547eaf7520>:
  spree_core (3.1.7) app/helpers/spree/base_helper.rb:71:in `method_missing'
  app/views/layouts/application.html.erb:29:in `_2d2c12f23c3eb61e155512f60fc14c09'
  actionview (4.2.9) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.9) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.9) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.9) lib/action_view/template.rb:143:in `render'
  deface (1.2.0) lib/deface/action_view_extensions.rb:41:in `render'
  actionview (4.2.9) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.9) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.9) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.9) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.9) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.9) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.9) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.9) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.9) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.9) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.9) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.9) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.9) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/kim/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.9) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.9) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/static_pages_controller.rb:20:in `show_index'
  app/controllers/static_pages_controller.rb:9:in `home'
  actionpack (4.2.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.9) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.9) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.9) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.9) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.9) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.9) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.9) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.9) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.9) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.9) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.9) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.9) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.9) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:817:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.9) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.9) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.9) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.9) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.9) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.9) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.9) lib/rails/engine.rb:518:in `call'
  railties (4.2.9) lib/rails/application.rb:165:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/handler/webrick.rb:88:in `service'
  /home/kim/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
  /home/kim/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
  /home/kim/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'



Started POST "/__better_errors/1513b5715f1fce90/variables" for 127.0.0.1 at 2017-08-08 12:07:28 +0100
```

Gemfile:

```
GIT
  remote: git://github.com/inopinatus/sass-rails-source-maps.git
  revision: eba1658f253ad3aa1a23e86df106998d7f981215
  specs:
    sass-rails-source-maps (0.1.0)
      rails
      sass (~> 3.3)
      sass-rails (~> 5.0.0.beta1)
      sprockets (>= 2.3.0)

GIT
  remote: git://github.com/sauliusgrigaitis/capistrano-db-tasks.git
  revision: bfe43bec3b16e7941b5c50a068e4ba2205ffd22a
  specs:
    capistrano-db-tasks (0.4)
      capistrano (>= 3.0.0)

GIT
  remote: git://github.com/spree-contrib/better_spree_paypal_express.git
  revision: f65c6a1ec43aaea59397b2419154a2c9a9bfb613
  specs:
    spree_paypal_express (3.1.0)
      paypal-sdk-merchant (= 1.106.1)
      spree_core (~> 3.1.0.beta)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.9)
      actionpack (= 4.2.9)
      actionview (= 4.2.9)
      activejob (= 4.2.9)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.9)
      actionview (= 4.2.9)
      activesupport (= 4.2.9)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.9)
      activesupport (= 4.2.9)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_link_to (1.0.4)
      actionpack
      addressable
    activeadmin (1.1.0)
      arbre (>= 1.1.1)
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.7)
      jquery-rails
      kaminari (>= 0.15, < 2.0)
      railties (>= 4.2, < 5.2)
      ransack (~> 1.3)
      sass (~> 3.1)
      sprockets (< 4.1)
    activejob (4.2.9)
      activesupport (= 4.2.9)
      globalid (>= 0.3.0)
    activemerchant (1.69.0)
      activesupport (>= 3.2.14, < 6.x)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (4.2.9)
      activesupport (= 4.2.9)
      builder (~> 3.1)
    activerecord (4.2.9)
      activemodel (= 4.2.9)
      activesupport (= 4.2.9)
      arel (~> 6.0)
    activesupport (4.2.9)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_list (0.9.7)
      activerecord (>= 3.0)
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    airbrussh (1.3.0)
      sshkit (>= 1.6.1, != 1.7.0)
    ansi (1.5.0)
    arbre (1.1.1)
      activesupport (>= 3.0.0)
    arel (6.0.4)
    autoprefixer-rails (7.1.2.4)
      execjs
    awesome_nested_set (3.0.3)
      activerecord (>= 4.0.0, < 5)
    bcrypt (3.1.11)
    better_errors (2.3.0)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.3)
    byebug (9.0.6)
    camertron-eprun (1.1.1)
    cancancan (1.10.1)
    canonical-rails (0.0.11)
      rails (>= 3.1, < 5.0)
    capistrano (3.6.1)
      airbrussh (>= 1.0.0)
      capistrano-harrow
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.2.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-harrow (0.5.3)
    capistrano-rails (1.3.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano3-puma (2.0.0)
      capistrano (~> 3.5)
      capistrano-bundler
      puma (~> 3.4)
    capybara (2.13.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.14.0)
      capybara (>= 2.3.0, < 2.14.0)
      json
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    cldr-plurals-runtime-rb (1.0.1)
    climate_control (0.2.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    css_parser (1.5.0)
      addressable
    database_cleaner (1.6.1)
    debug_inspector (0.0.3)
    deface (1.2.0)
      nokogiri (~> 1.6)
      polyglot
      rails (>= 4.1)
      rainbow (>= 2.1.0)
    docile (1.1.5)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.2.1)
    dotenv-rails (2.2.1)
      dotenv (= 2.2.1)
      railties (>= 3.2, < 5.2)
    erubi (1.6.1)
    erubis (2.7.0)
    execjs (2.7.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.8.0)
      factory_girl (~> 4.8.0)
      railties (>= 3.0.0)
    faraday (0.12.2)
      multipart-post (>= 1.2, < 3)
    ffaker (2.2.0)
    ffi (1.9.18)
    font-awesome-rails (4.7.0.2)
      railties (>= 3.2, < 5.2)
    formatador (0.2.5)
    formtastic (3.1.5)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.6.0)
    foundation-rails (5.5.3.2)
      railties (>= 3.1.0)
      sass (>= 3.3.0, < 3.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    gibbon (3.1.0)
      faraday (>= 0.9.1)
      multi_json (>= 1.11.0)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    guard (2.14.1)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-minitest (2.4.6)
      guard-compat (~> 1.2)
      minitest (>= 3.0)
    has_scope (0.7.1)
      actionpack (>= 4.1, < 5.2)
      activesupport (>= 4.1, < 5.2)
    highline (1.6.21)
    htmlentities (4.3.4)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    i18n (0.8.6)
    immigrant (0.3.6)
      activerecord (>= 3.0)
    inherited_resources (1.7.2)
      actionpack (>= 3.2, < 5.2.x)
      has_scope (~> 0.6)
      railties (>= 3.2, < 5.2.x)
      responders
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.6)
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    libv8 (3.16.14.19)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.12)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    mailgun_rails (0.9.0)
      actionmailer (>= 3.2.13)
      json (>= 1.7.7)
      rest-client (>= 1.6.7)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.0)
    mini_portile2 (2.2.0)
    minitest (5.10.3)
    minitest-rails (2.2.1)
      minitest (~> 5.7)
      railties (~> 4.1)
    minitest-reporters (1.1.14)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    monetize (1.7.0)
      money (~> 6.9)
    money (6.9.0)
      i18n (>= 0.6.4, < 0.9)
    mountain_view (0.12.2)
      rails (>= 3.2.0)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.1.0)
    netrc (0.11.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    paperclip (4.3.7)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)
    paranoia (2.1.5)
      activerecord (~> 4.0)
    paypal-sdk-core (0.2.10)
      multi_json (~> 1.0)
      xml-simple
    paypal-sdk-merchant (1.106.1)
      paypal-sdk-core (~> 0.2.3)
    pg (0.21.0)
    polyamorous (1.3.1)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    premailer (1.10.4)
      addressable
      css_parser (>= 1.4.10)
      htmlentities (>= 4.0.0)
    premailer-rails (1.9.7)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    public_suffix (2.0.5)
    puma (3.9.1)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rabl (0.12.0)
      activesupport (>= 2.3.14)
    rack (1.6.8)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.9)
      actionmailer (= 4.2.9)
      actionpack (= 4.2.9)
      actionview (= 4.2.9)
      activejob (= 4.2.9)
      activemodel (= 4.2.9)
      activerecord (= 4.2.9)
      activesupport (= 4.2.9)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.9)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (4.2.9)
      actionpack (= 4.2.9)
      activesupport (= 4.2.9)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.2.2)
      rake
    rake (12.0.0)
    ransack (1.4.1)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rdoc (4.3.0)
    redcarpet (3.4.0)
    ref (2.0.0)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    ruby-oembed (0.12.0)
    ruby-progressbar (1.8.1)
    ruby_dep (1.5.0)
    sass (3.4.25)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    shellany (0.0.1)
    simplecov (0.14.1)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.1)
    slop (3.6.0)
    spree (3.1.7)
      spree_api (= 3.1.7)
      spree_backend (= 3.1.7)
      spree_cmd (= 3.1.7)
      spree_core (= 3.1.7)
      spree_frontend (= 3.1.7)
      spree_sample (= 3.1.7)
    spree_api (3.1.7)
      rabl (~> 0.12.0)
      spree_core (= 3.1.7)
      versioncake (~> 2.3.1)
    spree_backend (3.1.7)
      bootstrap-sass (~> 3.3)
      jquery-rails (~> 4.1)
      jquery-ui-rails (~> 5.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.1.7)
      spree_core (= 3.1.7)
    spree_cmd (3.1.7)
      thor (~> 0.14)
    spree_core (3.1.7)
      activemerchant (~> 1.59)
      acts_as_list (~> 0.7, >= 0.7.2)
      awesome_nested_set (~> 3.0.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0)
      ffaker (~> 2.2.0)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      kaminari (~> 0.17)
      monetize (~> 1.1)
      paperclip (~> 4.3.0)
      paranoia (~> 2.1.0)
      premailer-rails
      rails (~> 4.2.5)
      ransack (~> 1.4.1)
      responders
      sprockets-rails
      state_machines-activerecord (~> 0.2)
      stringex
      truncate_html (~> 0.9.3)
      twitter_cldr (~> 3.0)
    spree_extension (0.0.5)
      activerecord (>= 4.2)
    spree_frontend (3.1.7)
      bootstrap-sass (>= 3.3.5.1, < 3.4)
      canonical-rails (~> 0.0.4)
      jquery-rails (~> 4.1)
      spree_api (= 3.1.7)
      spree_core (= 3.1.7)
    spree_gateway (3.3.0)
      spree_core (>= 3.1.0, < 4.0)
      spree_extension
    spree_sample (3.1.7)
      spree_core (= 3.1.7)
    spring (2.0.2)
      activesupport (>= 4.2)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.14.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.5.0)
      activemodel (>= 4.1, < 5.2)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.5.0)
      activerecord (>= 4.1, < 5.2)
      state_machines-activemodel (>= 0.5.0)
    stringex (2.7.1)
    susy (2.2.12)
      sass (>= 3.3.0, < 3.5)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.8)
    truncate_html (0.9.3)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.3)
    twitter_cldr (3.6.0)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0)
      tzinfo
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    versioncake (2.3.1)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xml-simple (1.1.5)
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_link_to
  activeadmin
  bcrypt (~> 3.1.7)
  better_errors
  byebug
  capistrano (~> 3.6.1)
  capistrano-bundler
  capistrano-db-tasks!
  capistrano-rails
  capistrano-rvm
  capistrano3-puma
  capybara
  capybara-webkit
  coffee-rails (~> 4.1.0)
  database_cleaner
  dotenv-rails
  factory_girl_rails
  ffaker
  foundation-rails (~> 5.5)
  friendly_id (~> 5.1.0)
  gibbon
  guard
  guard-minitest
  immigrant
  jbuilder (~> 2.0)
  jquery-rails
  jquery-turbolinks
  launchy
  mailgun_rails
  minitest-rails
  minitest-reporters
  mountain_view
  pg
  puma
  quiet_assets
  rails (~> 4)
  rails_12factor
  redcarpet
  ruby-oembed
  sass-rails
  sass-rails-source-maps!
  sdoc (~> 0.4.0)
  simplecov
  spree (~> 3.1)
  spree_gateway (~> 3.1)
  spree_paypal_express!
  spring
  susy
  therubyracer
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

RUBY VERSION
   ruby 2.4.1p111

BUNDLED WITH
   1.15.3
```

**Comment by kimadactyl** [comment]
Hmm, I just tried this on a fresh-ish rails install and it works fine. Presumably some gem clash... ugh argh.

**Comment by kitop** [comment]
@kimadactyl I see you're using Rails 4.2 there. Did it work when you tried in a new 5.1 instance?

**Comment by kimadactyl** [comment]
Oh right, yes, that would be it, bit slow today :)

**Comment by kitop** [comment]
Can you try it in a brand-new Rails 4.2 application without spree?

**Comment by kimadactyl** [comment]
Just tried it and it's working fine :( do you think it is Spree causing the issue? All I can think is that that uses a mount directive. Maybe a clash?

**Comment by kitop** [comment]
@kimadactyl mhm... that's interesting... It may be related to #51, #52, and #53.

Are you trying to render the component from a Spree controller?
Not sure what Spree is doing, but if it doesn't inherit from `ActionController::Base`, you may need to manually include those helpers.

**Comment by kimadactyl** [comment]
No, just rendering it from `application.html.erb` at the moment. Hmmmmmmmmm.

**Comment by kitop** [comment]
Can you try adding
```ruby
helper MountainView::ComponentHelper
```
to your `ApplicationController`?

**Comment by kimadactyl** [comment]
That's got it, thanks again! :1st_place_medal:

**Comment by kitop** [comment]
:D Great!!
Will add a workaround for 4.2 in the gem soon!
